# Generated by Django 4.2.26 on 2025-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_birthday',
            field=models.BooleanField(default=False, help_text='Check for birthdays'),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('yearly', 'Every year (birthdays, anniversaries)'), ('monthly', 'Every month'), ('weekly', 'Every week')], default='none', max_length=20),
        ),
    ]
